# Generated by Django 3.2.13 on 2022-06-21 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_comment_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cook_time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='prep_time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='serves',
        ),
    ]
